# Python stub file for the contact extension module

def contact(searchWidth: int, threshold: float, rows: int, cols: int, dilS: ctypes._Pointer, dilO: ctypes._Pointer, maskS: ctypes._Pointer, maskO: ctypes._Pointer, depthImg: ctypes._Pointer, contPS: ctypes._Pointer, contPO: ctypes._Pointer) -> None: ...
